<?php require_once("../resources/config.php"); ?>

<?php require_once("resources/cart_functions.php"); ?>

<?php 

    // if we can get transaction Identifier('tx'),
    if(isset($_GET['tx'])){

        $amount = filter_input(INPUT_GET, 'amt', FILTER_SANITIZE_NUMBER_FLOAT);
        $currency = filter_input(INPUT_GET, 'cc', FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $transaction = filter_input(INPUT_GET, 'tx', FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $status = filter_input(INPUT_GET, 'st', FILTER_SANITIZE_FULL_SPECIAL_CHARS);

        if($_SESSION['amount']){

            // Insert data into Database in orders table
            $query = "INSERT INTO orders (amount, currency, transaction, status, firstname, lastname, address, address2, towncity, province, postal, phone) 
                            VALUES (:amount, :currency, :transaction, :status, :firstname, :lastname, :address, :address2, :towncity, :province, :postal, :phone)";
            $statement = $db->preapre($query);
            $bind_values = ['amount' => $amount, 'currency' => $currency, 'transaction' => $transaction, 'status' => $status, 'firstname' => $_SESSION['firstname'], 'lastname' => $_SESSION['lastname'], 'address' => $_SESSION['address'], 'address2' => $_SESSION['address2'], 'towncity' => $_SESSION['towncity'], 'province' => $_SESSION['province'], 'postal' => $_SESSION['postal'], 'phone' => $_SESSION['phone']];
            $statement->exectue($bind_values);

        }else{
            session_destroy();
            header("Location: index.php");
        }

        // reset total and item_quantity 
        $total = 0;
        $item_quantity = 0;

        // generated by function in functions.php as global id that is used to be inserted into report table in database
        // last_id == order_id which can be matched with oder_id in orders table
        $last_id = last_id();

 ?>

<link rel="stylesheet" type="text/css" href="css/mysytles.css">

<!-- Header Section -->
<?php include(TEMPLATE_FRONT . DS . "header.php"); ?>
		
	<div class="hero-wrap hero-bread" style="background-image: url('images/bg_6.jpg');">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-0 bread">My Order</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.php">Home</a></span> <span>Order</span></p>
          </div>
        </div>
      </div>
    </div>
	<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
	<input type="hidden" name="cmd" value="_cart">
	<input type="hidden" name="business" value="sb-f7ygs09627@business.example.com">
	<input type="hidden" name="currency_code" value="CAD">
		<section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">

    				<div class="cart-list">
	    				<table class="table">
	    					
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>Image</th>
						        <th>Product</th>
						        <th>Price</th>
						        <th>Quantity</th>
						        <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>

						      

        foreach ($_SESSION as $name => $value) {

            if($value > 0){

                if(substr($name, 0, 8) == "product_"){
                    $length = strlen($name) - 8;
                    $id = substr($name, 8, $length);

                    $query = query("SELECT * FROM products WHERE product_id = " . escape_string($id) . " ");
                    confirm($query);

                    while($row = fetch_array($query)){
                        $sub = $row['product_price'] * $value;
                        $item_quantity += $value;

                        // Insert data into Database in reports table
                        //$id is already defined above
                        $product_price = $row['product_price'];
                        $product_title = $row['product_title'];
                        //$value is already defined above

                        $insert_report = query("INSERT INTO reports (product_id, order_id, product_title, product_price, product_quantity, sub_total) 
                                                VALUES ('{$id}', '{$last_id}', '{$product_title}', '{$product_price}', '{$value}', '{$sub}') ");
                        confirm($insert_report);

                        // display orders to the customer
                        $product =<<<DELIMETER
                        <tr class="text-center">

                            <td class="image-prod"><img width="100" src="resources/uploads/{$row['product_image']}" alt="image"/></td>

                            <td class="product-name">
                                <h3>{$row['product_title']}</h3>
                                <p>{$row['product_short_desc']}</p>
                            </td>
                            <td class="price">&#36;{$row['product_price']}</td>
                            <td class="quantity">
                                <div class="input-group mb-3">
                                    <input type="text" name="quantity" class="quantity form-control input-number" value="{$value}" min="1" max="100">
                                </div>
                            </td>
                            <td class="total">&#36;{$sub}</td>
                        </tr>
DELIMETER;
                        echo $product;

                    }
                    $total += $sub;
                }
            }
        }
        // end of foreach loop for inserting and displaying data
    session_destroy();

    }else{
        // if there is no transaction data, go to index.php
        redirect("index.php");
    }
						      
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    		<div class="row justify-content-end">
    			<div class="col col-lg-5 col-md-6 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">
    					<h3>Order Totals</h3>
    					<p class="d-flex">
    						<span>Items</span>
    						<span>
    							<?= isset($_SESSION['item_quantity']) ? $_SESSION['item_quantity'] : $_SESSION['item_quantity'] = "0"; ?>
    						</span>
    					</p>
    					<p class="d-flex">
    						<span>Delivery</span>
    						<span>Free Shipping</span>
    					</p>
    					<!-- <p class="d-flex">
    						<span>Discount</span>
    						<span>$3.00</span>
    					</p> -->
    					<hr>
    					<p class="d-flex total-price">
    						<span>Total</span>
    						<span id="totalAmount">&#36;
    							<?php isset($_SESSION['item_total']) ? $_SESSION['item_total'] : $_SESSION['item_total'] = "0"; ?>
    						</span>
    					</p>
    				</div>
    				
    			</div>
    		</div>
			</div>
		</section>
	</form>
    
<?php 

foreach ($_SESSION as $name => $value){
	debug_to_console($name);
	debug_to_console($value);
}

?>
    
<!-- Footer Section -->	
<?php include(TEMPLATE_FRONT . DS . "footer.php"); ?>